// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Story2Config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Story2Config.proto</summary>
public static partial class Story2ConfigReflection {

  #region Descriptor
  /// <summary>File descriptor for Story2Config.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static Story2ConfigReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJTdG9yeTJDb25maWcucHJvdG8iMAoRU3RvcnkyQ29uZmlnRGF0YXMSGwoE",
          "QmFzZRgBIAMoCzINLlN0b3J5MkNvbmZpZyLOAgoMU3RvcnkyQ29uZmlnEgoK",
          "AklEGAEgASgFEgwKBERlc2MYAiABKAkSEwoLVGFsa2lkQXJyYXkYAyADKAUS",
          "DwoHT3B0dHlwZRgEIAEoBRIPCgdPcHR0ZXh0GAUgASgJEhEKCVN0b3J5ME9w",
          "dBgGIAEoCRISCgpTdG9yeTBKdW1wGAcgASgFEhIKClN0b3J5MEdvb2QYCCAB",
          "KAUSEgoKU3RvcnkxT3B0MRgJIAEoCRISCgpTdG9yeTFPcHQyGAogASgFEhIK",
          "ClN0b3J5MU9wdDMYCyABKAUSEgoKU3RvcnkxT3B0NBgMIAEoCRISCgpTdG9y",
          "eTFPcHQ1GA0gASgFEhIKClN0b3J5MU9wdDYYDiABKAUSEgoKU3RvcnkxT3B0",
          "NxgPIAEoCRISCgpTdG9yeTFPcHQ4GBAgASgFEhIKClN0b3J5MU9wdDkYESAB",
          "KAViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Story2ConfigDatas), global::Story2ConfigDatas.Parser, new[]{ "Base" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Story2Config), global::Story2Config.Parser, new[]{ "ID", "Desc", "TalkidArray", "Opttype", "Opttext", "Story0Opt", "Story0Jump", "Story0Good", "Story1Opt1", "Story1Opt2", "Story1Opt3", "Story1Opt4", "Story1Opt5", "Story1Opt6", "Story1Opt7", "Story1Opt8", "Story1Opt9" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Story2ConfigDatas : pb::IMessage<Story2ConfigDatas> {
  private static readonly pb::MessageParser<Story2ConfigDatas> _parser = new pb::MessageParser<Story2ConfigDatas>(() => new Story2ConfigDatas());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Story2ConfigDatas> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Story2ConfigReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Story2ConfigDatas() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Story2ConfigDatas(Story2ConfigDatas other) : this() {
    base_ = other.base_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Story2ConfigDatas Clone() {
    return new Story2ConfigDatas(this);
  }

  /// <summary>Field number for the "Base" field.</summary>
  public const int BaseFieldNumber = 1;
  private static readonly pb::FieldCodec<global::Story2Config> _repeated_base_codec
      = pb::FieldCodec.ForMessage(10, global::Story2Config.Parser);
  private readonly pbc::RepeatedField<global::Story2Config> base_ = new pbc::RepeatedField<global::Story2Config>();
  /// <summary>
  ///Base===>Story2Config类的数组列表类
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::Story2Config> Base {
    get { return base_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Story2ConfigDatas);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Story2ConfigDatas other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!base_.Equals(other.base_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= base_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    base_.WriteTo(output, _repeated_base_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += base_.CalculateSize(_repeated_base_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Story2ConfigDatas other) {
    if (other == null) {
      return;
    }
    base_.Add(other.base_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          base_.AddEntriesFrom(input, _repeated_base_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class Story2Config : pb::IMessage<Story2Config> {
  private static readonly pb::MessageParser<Story2Config> _parser = new pb::MessageParser<Story2Config>(() => new Story2Config());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Story2Config> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Story2ConfigReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Story2Config() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Story2Config(Story2Config other) : this() {
    iD_ = other.iD_;
    desc_ = other.desc_;
    talkidArray_ = other.talkidArray_.Clone();
    opttype_ = other.opttype_;
    opttext_ = other.opttext_;
    story0Opt_ = other.story0Opt_;
    story0Jump_ = other.story0Jump_;
    story0Good_ = other.story0Good_;
    story1Opt1_ = other.story1Opt1_;
    story1Opt2_ = other.story1Opt2_;
    story1Opt3_ = other.story1Opt3_;
    story1Opt4_ = other.story1Opt4_;
    story1Opt5_ = other.story1Opt5_;
    story1Opt6_ = other.story1Opt6_;
    story1Opt7_ = other.story1Opt7_;
    story1Opt8_ = other.story1Opt8_;
    story1Opt9_ = other.story1Opt9_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Story2Config Clone() {
    return new Story2Config(this);
  }

  /// <summary>Field number for the "ID" field.</summary>
  public const int IDFieldNumber = 1;
  private int iD_;
  /// <summary>
  ///ID===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ID {
    get { return iD_; }
    set {
      iD_ = value;
    }
  }

  /// <summary>Field number for the "Desc" field.</summary>
  public const int DescFieldNumber = 2;
  private string desc_ = "";
  /// <summary>
  ///Desc===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Desc {
    get { return desc_; }
    set {
      desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "TalkidArray" field.</summary>
  public const int TalkidArrayFieldNumber = 3;
  private static readonly pb::FieldCodec<int> _repeated_talkidArray_codec
      = pb::FieldCodec.ForInt32(26);
  private readonly pbc::RepeatedField<int> talkidArray_ = new pbc::RepeatedField<int>();
  /// <summary>
  ///TalkidArray===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<int> TalkidArray {
    get { return talkidArray_; }
  }

  /// <summary>Field number for the "Opttype" field.</summary>
  public const int OpttypeFieldNumber = 4;
  private int opttype_;
  /// <summary>
  ///Opttype===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Opttype {
    get { return opttype_; }
    set {
      opttype_ = value;
    }
  }

  /// <summary>Field number for the "Opttext" field.</summary>
  public const int OpttextFieldNumber = 5;
  private string opttext_ = "";
  /// <summary>
  ///Opttext===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Opttext {
    get { return opttext_; }
    set {
      opttext_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Story0Opt" field.</summary>
  public const int Story0OptFieldNumber = 6;
  private string story0Opt_ = "";
  /// <summary>
  ///Story0Opt===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Story0Opt {
    get { return story0Opt_; }
    set {
      story0Opt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Story0Jump" field.</summary>
  public const int Story0JumpFieldNumber = 7;
  private int story0Jump_;
  /// <summary>
  ///Story0Jump===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Story0Jump {
    get { return story0Jump_; }
    set {
      story0Jump_ = value;
    }
  }

  /// <summary>Field number for the "Story0Good" field.</summary>
  public const int Story0GoodFieldNumber = 8;
  private int story0Good_;
  /// <summary>
  ///Story0Good===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Story0Good {
    get { return story0Good_; }
    set {
      story0Good_ = value;
    }
  }

  /// <summary>Field number for the "Story1Opt1" field.</summary>
  public const int Story1Opt1FieldNumber = 9;
  private string story1Opt1_ = "";
  /// <summary>
  ///Story1Opt1===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Story1Opt1 {
    get { return story1Opt1_; }
    set {
      story1Opt1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Story1Opt2" field.</summary>
  public const int Story1Opt2FieldNumber = 10;
  private int story1Opt2_;
  /// <summary>
  ///Story1Opt2===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Story1Opt2 {
    get { return story1Opt2_; }
    set {
      story1Opt2_ = value;
    }
  }

  /// <summary>Field number for the "Story1Opt3" field.</summary>
  public const int Story1Opt3FieldNumber = 11;
  private int story1Opt3_;
  /// <summary>
  ///Story1Opt3===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Story1Opt3 {
    get { return story1Opt3_; }
    set {
      story1Opt3_ = value;
    }
  }

  /// <summary>Field number for the "Story1Opt4" field.</summary>
  public const int Story1Opt4FieldNumber = 12;
  private string story1Opt4_ = "";
  /// <summary>
  ///Story1Opt4===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Story1Opt4 {
    get { return story1Opt4_; }
    set {
      story1Opt4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Story1Opt5" field.</summary>
  public const int Story1Opt5FieldNumber = 13;
  private int story1Opt5_;
  /// <summary>
  ///Story1Opt5===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Story1Opt5 {
    get { return story1Opt5_; }
    set {
      story1Opt5_ = value;
    }
  }

  /// <summary>Field number for the "Story1Opt6" field.</summary>
  public const int Story1Opt6FieldNumber = 14;
  private int story1Opt6_;
  /// <summary>
  ///Story1Opt6===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Story1Opt6 {
    get { return story1Opt6_; }
    set {
      story1Opt6_ = value;
    }
  }

  /// <summary>Field number for the "Story1Opt7" field.</summary>
  public const int Story1Opt7FieldNumber = 15;
  private string story1Opt7_ = "";
  /// <summary>
  ///Story1Opt7===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Story1Opt7 {
    get { return story1Opt7_; }
    set {
      story1Opt7_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Story1Opt8" field.</summary>
  public const int Story1Opt8FieldNumber = 16;
  private int story1Opt8_;
  /// <summary>
  ///Story1Opt8===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Story1Opt8 {
    get { return story1Opt8_; }
    set {
      story1Opt8_ = value;
    }
  }

  /// <summary>Field number for the "Story1Opt9" field.</summary>
  public const int Story1Opt9FieldNumber = 17;
  private int story1Opt9_;
  /// <summary>
  ///Story1Opt9===>ohh
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Story1Opt9 {
    get { return story1Opt9_; }
    set {
      story1Opt9_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Story2Config);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Story2Config other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ID != other.ID) return false;
    if (Desc != other.Desc) return false;
    if(!talkidArray_.Equals(other.talkidArray_)) return false;
    if (Opttype != other.Opttype) return false;
    if (Opttext != other.Opttext) return false;
    if (Story0Opt != other.Story0Opt) return false;
    if (Story0Jump != other.Story0Jump) return false;
    if (Story0Good != other.Story0Good) return false;
    if (Story1Opt1 != other.Story1Opt1) return false;
    if (Story1Opt2 != other.Story1Opt2) return false;
    if (Story1Opt3 != other.Story1Opt3) return false;
    if (Story1Opt4 != other.Story1Opt4) return false;
    if (Story1Opt5 != other.Story1Opt5) return false;
    if (Story1Opt6 != other.Story1Opt6) return false;
    if (Story1Opt7 != other.Story1Opt7) return false;
    if (Story1Opt8 != other.Story1Opt8) return false;
    if (Story1Opt9 != other.Story1Opt9) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ID != 0) hash ^= ID.GetHashCode();
    if (Desc.Length != 0) hash ^= Desc.GetHashCode();
    hash ^= talkidArray_.GetHashCode();
    if (Opttype != 0) hash ^= Opttype.GetHashCode();
    if (Opttext.Length != 0) hash ^= Opttext.GetHashCode();
    if (Story0Opt.Length != 0) hash ^= Story0Opt.GetHashCode();
    if (Story0Jump != 0) hash ^= Story0Jump.GetHashCode();
    if (Story0Good != 0) hash ^= Story0Good.GetHashCode();
    if (Story1Opt1.Length != 0) hash ^= Story1Opt1.GetHashCode();
    if (Story1Opt2 != 0) hash ^= Story1Opt2.GetHashCode();
    if (Story1Opt3 != 0) hash ^= Story1Opt3.GetHashCode();
    if (Story1Opt4.Length != 0) hash ^= Story1Opt4.GetHashCode();
    if (Story1Opt5 != 0) hash ^= Story1Opt5.GetHashCode();
    if (Story1Opt6 != 0) hash ^= Story1Opt6.GetHashCode();
    if (Story1Opt7.Length != 0) hash ^= Story1Opt7.GetHashCode();
    if (Story1Opt8 != 0) hash ^= Story1Opt8.GetHashCode();
    if (Story1Opt9 != 0) hash ^= Story1Opt9.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ID);
    }
    if (Desc.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Desc);
    }
    talkidArray_.WriteTo(output, _repeated_talkidArray_codec);
    if (Opttype != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Opttype);
    }
    if (Opttext.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Opttext);
    }
    if (Story0Opt.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Story0Opt);
    }
    if (Story0Jump != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Story0Jump);
    }
    if (Story0Good != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(Story0Good);
    }
    if (Story1Opt1.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(Story1Opt1);
    }
    if (Story1Opt2 != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(Story1Opt2);
    }
    if (Story1Opt3 != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(Story1Opt3);
    }
    if (Story1Opt4.Length != 0) {
      output.WriteRawTag(98);
      output.WriteString(Story1Opt4);
    }
    if (Story1Opt5 != 0) {
      output.WriteRawTag(104);
      output.WriteInt32(Story1Opt5);
    }
    if (Story1Opt6 != 0) {
      output.WriteRawTag(112);
      output.WriteInt32(Story1Opt6);
    }
    if (Story1Opt7.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(Story1Opt7);
    }
    if (Story1Opt8 != 0) {
      output.WriteRawTag(128, 1);
      output.WriteInt32(Story1Opt8);
    }
    if (Story1Opt9 != 0) {
      output.WriteRawTag(136, 1);
      output.WriteInt32(Story1Opt9);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ID);
    }
    if (Desc.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
    }
    size += talkidArray_.CalculateSize(_repeated_talkidArray_codec);
    if (Opttype != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Opttype);
    }
    if (Opttext.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Opttext);
    }
    if (Story0Opt.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Story0Opt);
    }
    if (Story0Jump != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Story0Jump);
    }
    if (Story0Good != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Story0Good);
    }
    if (Story1Opt1.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Story1Opt1);
    }
    if (Story1Opt2 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Story1Opt2);
    }
    if (Story1Opt3 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Story1Opt3);
    }
    if (Story1Opt4.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Story1Opt4);
    }
    if (Story1Opt5 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Story1Opt5);
    }
    if (Story1Opt6 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Story1Opt6);
    }
    if (Story1Opt7.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Story1Opt7);
    }
    if (Story1Opt8 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Story1Opt8);
    }
    if (Story1Opt9 != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Story1Opt9);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Story2Config other) {
    if (other == null) {
      return;
    }
    if (other.ID != 0) {
      ID = other.ID;
    }
    if (other.Desc.Length != 0) {
      Desc = other.Desc;
    }
    talkidArray_.Add(other.talkidArray_);
    if (other.Opttype != 0) {
      Opttype = other.Opttype;
    }
    if (other.Opttext.Length != 0) {
      Opttext = other.Opttext;
    }
    if (other.Story0Opt.Length != 0) {
      Story0Opt = other.Story0Opt;
    }
    if (other.Story0Jump != 0) {
      Story0Jump = other.Story0Jump;
    }
    if (other.Story0Good != 0) {
      Story0Good = other.Story0Good;
    }
    if (other.Story1Opt1.Length != 0) {
      Story1Opt1 = other.Story1Opt1;
    }
    if (other.Story1Opt2 != 0) {
      Story1Opt2 = other.Story1Opt2;
    }
    if (other.Story1Opt3 != 0) {
      Story1Opt3 = other.Story1Opt3;
    }
    if (other.Story1Opt4.Length != 0) {
      Story1Opt4 = other.Story1Opt4;
    }
    if (other.Story1Opt5 != 0) {
      Story1Opt5 = other.Story1Opt5;
    }
    if (other.Story1Opt6 != 0) {
      Story1Opt6 = other.Story1Opt6;
    }
    if (other.Story1Opt7.Length != 0) {
      Story1Opt7 = other.Story1Opt7;
    }
    if (other.Story1Opt8 != 0) {
      Story1Opt8 = other.Story1Opt8;
    }
    if (other.Story1Opt9 != 0) {
      Story1Opt9 = other.Story1Opt9;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ID = input.ReadInt32();
          break;
        }
        case 18: {
          Desc = input.ReadString();
          break;
        }
        case 26:
        case 24: {
          talkidArray_.AddEntriesFrom(input, _repeated_talkidArray_codec);
          break;
        }
        case 32: {
          Opttype = input.ReadInt32();
          break;
        }
        case 42: {
          Opttext = input.ReadString();
          break;
        }
        case 50: {
          Story0Opt = input.ReadString();
          break;
        }
        case 56: {
          Story0Jump = input.ReadInt32();
          break;
        }
        case 64: {
          Story0Good = input.ReadInt32();
          break;
        }
        case 74: {
          Story1Opt1 = input.ReadString();
          break;
        }
        case 80: {
          Story1Opt2 = input.ReadInt32();
          break;
        }
        case 88: {
          Story1Opt3 = input.ReadInt32();
          break;
        }
        case 98: {
          Story1Opt4 = input.ReadString();
          break;
        }
        case 104: {
          Story1Opt5 = input.ReadInt32();
          break;
        }
        case 112: {
          Story1Opt6 = input.ReadInt32();
          break;
        }
        case 122: {
          Story1Opt7 = input.ReadString();
          break;
        }
        case 128: {
          Story1Opt8 = input.ReadInt32();
          break;
        }
        case 136: {
          Story1Opt9 = input.ReadInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
