// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WingUpLevel1Config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from WingUpLevel1Config.proto</summary>
public static partial class WingUpLevel1ConfigReflection {

  #region Descriptor
  /// <summary>File descriptor for WingUpLevel1Config.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static WingUpLevel1ConfigReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChhXaW5nVXBMZXZlbDFDb25maWcucHJvdG8iRAoXV2luZ1VwTGV2ZWwxQ29u",
          "ZmlnRGF0YXMSKQoMV2luZ1VwTGV2ZWwxGAEgAygLMhMuV2luZ1VwTGV2ZWwx",
          "Q29uZmlnIsgBChJXaW5nVXBMZXZlbDFDb25maWcSDgoGV2luZ0lkGAEgASgF",
          "EhAKCEZpZ2h0aW5nGAIgASgFEhEKCUltYWdlTmFtZRgDIAEoCRInCghJdGVt",
          "SW5mbxgEIAMoCzIVLldpbmdVcExldmVsMUl0ZW1JbmZvEg0KBVBhcmFtGAUg",
          "AygFEhIKCldpbmdOYW1lSWQYBiABKAUSHQoDQUFBGAcgAygLMhAuV2luZ1Vw",
          "TGV2ZWwxQUFBEhIKCkludDY0VmFsdWUYCCABKAMiNwoUV2luZ1VwTGV2ZWwx",
          "SXRlbUluZm8SDgoGSXRlbUlkGAEgASgNEg8KB0l0ZW1OdW0YAiABKA0iTQoP",
          "V2luZ1VwTGV2ZWwxQUFBEgoKAkExGAEgASgFEg4KBlVpbnRBMhgCIAEoDRIK",
          "CgJBMxgDIAEoCRISCgpSZXBlYXRlZEE0GAQgAygJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::WingUpLevel1ConfigDatas), global::WingUpLevel1ConfigDatas.Parser, new[]{ "WingUpLevel1" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WingUpLevel1Config), global::WingUpLevel1Config.Parser, new[]{ "WingId", "Fighting", "ImageName", "ItemInfo", "Param", "WingNameId", "AAA", "Int64Value" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WingUpLevel1ItemInfo), global::WingUpLevel1ItemInfo.Parser, new[]{ "ItemId", "ItemNum" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WingUpLevel1AAA), global::WingUpLevel1AAA.Parser, new[]{ "A1", "UintA2", "A3", "RepeatedA4" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class WingUpLevel1ConfigDatas : pb::IMessage<WingUpLevel1ConfigDatas> {
  private static readonly pb::MessageParser<WingUpLevel1ConfigDatas> _parser = new pb::MessageParser<WingUpLevel1ConfigDatas>(() => new WingUpLevel1ConfigDatas());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<WingUpLevel1ConfigDatas> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WingUpLevel1ConfigReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WingUpLevel1ConfigDatas() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WingUpLevel1ConfigDatas(WingUpLevel1ConfigDatas other) : this() {
    wingUpLevel1_ = other.wingUpLevel1_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WingUpLevel1ConfigDatas Clone() {
    return new WingUpLevel1ConfigDatas(this);
  }

  /// <summary>Field number for the "WingUpLevel1" field.</summary>
  public const int WingUpLevel1FieldNumber = 1;
  private static readonly pb::FieldCodec<global::WingUpLevel1Config> _repeated_wingUpLevel1_codec
      = pb::FieldCodec.ForMessage(10, global::WingUpLevel1Config.Parser);
  private readonly pbc::RepeatedField<global::WingUpLevel1Config> wingUpLevel1_ = new pbc::RepeatedField<global::WingUpLevel1Config>();
  /// <summary>
  ///WingUpLevel1===>WingUpLevel1Config类的数组列表类
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::WingUpLevel1Config> WingUpLevel1 {
    get { return wingUpLevel1_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as WingUpLevel1ConfigDatas);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(WingUpLevel1ConfigDatas other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!wingUpLevel1_.Equals(other.wingUpLevel1_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= wingUpLevel1_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    wingUpLevel1_.WriteTo(output, _repeated_wingUpLevel1_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += wingUpLevel1_.CalculateSize(_repeated_wingUpLevel1_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(WingUpLevel1ConfigDatas other) {
    if (other == null) {
      return;
    }
    wingUpLevel1_.Add(other.wingUpLevel1_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          wingUpLevel1_.AddEntriesFrom(input, _repeated_wingUpLevel1_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class WingUpLevel1Config : pb::IMessage<WingUpLevel1Config> {
  private static readonly pb::MessageParser<WingUpLevel1Config> _parser = new pb::MessageParser<WingUpLevel1Config>(() => new WingUpLevel1Config());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<WingUpLevel1Config> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WingUpLevel1ConfigReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WingUpLevel1Config() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WingUpLevel1Config(WingUpLevel1Config other) : this() {
    wingId_ = other.wingId_;
    fighting_ = other.fighting_;
    imageName_ = other.imageName_;
    itemInfo_ = other.itemInfo_.Clone();
    param_ = other.param_.Clone();
    wingNameId_ = other.wingNameId_;
    aAA_ = other.aAA_.Clone();
    int64Value_ = other.int64Value_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WingUpLevel1Config Clone() {
    return new WingUpLevel1Config(this);
  }

  /// <summary>Field number for the "WingId" field.</summary>
  public const int WingIdFieldNumber = 1;
  private int wingId_;
  /// <summary>
  ///WingId===>羽翼id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int WingId {
    get { return wingId_; }
    set {
      wingId_ = value;
    }
  }

  /// <summary>Field number for the "Fighting" field.</summary>
  public const int FightingFieldNumber = 2;
  private int fighting_;
  /// <summary>
  ///Fighting===>战斗力
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Fighting {
    get { return fighting_; }
    set {
      fighting_ = value;
    }
  }

  /// <summary>Field number for the "ImageName" field.</summary>
  public const int ImageNameFieldNumber = 3;
  private string imageName_ = "";
  /// <summary>
  ///ImageName===>图片名
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ImageName {
    get { return imageName_; }
    set {
      imageName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ItemInfo" field.</summary>
  public const int ItemInfoFieldNumber = 4;
  private static readonly pb::FieldCodec<global::WingUpLevel1ItemInfo> _repeated_itemInfo_codec
      = pb::FieldCodec.ForMessage(34, global::WingUpLevel1ItemInfo.Parser);
  private readonly pbc::RepeatedField<global::WingUpLevel1ItemInfo> itemInfo_ = new pbc::RepeatedField<global::WingUpLevel1ItemInfo>();
  /// <summary>
  ///ItemInfo===>
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::WingUpLevel1ItemInfo> ItemInfo {
    get { return itemInfo_; }
  }

  /// <summary>Field number for the "Param" field.</summary>
  public const int ParamFieldNumber = 5;
  private static readonly pb::FieldCodec<int> _repeated_param_codec
      = pb::FieldCodec.ForInt32(42);
  private readonly pbc::RepeatedField<int> param_ = new pbc::RepeatedField<int>();
  /// <summary>
  ///Param===>其他参数
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<int> Param {
    get { return param_; }
  }

  /// <summary>Field number for the "WingNameId" field.</summary>
  public const int WingNameIdFieldNumber = 6;
  private int wingNameId_;
  /// <summary>
  ///WingNameId===>羽翼名称id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int WingNameId {
    get { return wingNameId_; }
    set {
      wingNameId_ = value;
    }
  }

  /// <summary>Field number for the "AAA" field.</summary>
  public const int AAAFieldNumber = 7;
  private static readonly pb::FieldCodec<global::WingUpLevel1AAA> _repeated_aAA_codec
      = pb::FieldCodec.ForMessage(58, global::WingUpLevel1AAA.Parser);
  private readonly pbc::RepeatedField<global::WingUpLevel1AAA> aAA_ = new pbc::RepeatedField<global::WingUpLevel1AAA>();
  /// <summary>
  ///AAA===>
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::WingUpLevel1AAA> AAA {
    get { return aAA_; }
  }

  /// <summary>Field number for the "Int64Value" field.</summary>
  public const int Int64ValueFieldNumber = 8;
  private long int64Value_;
  /// <summary>
  ///Int64Value===>Int64Value
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long Int64Value {
    get { return int64Value_; }
    set {
      int64Value_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as WingUpLevel1Config);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(WingUpLevel1Config other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (WingId != other.WingId) return false;
    if (Fighting != other.Fighting) return false;
    if (ImageName != other.ImageName) return false;
    if(!itemInfo_.Equals(other.itemInfo_)) return false;
    if(!param_.Equals(other.param_)) return false;
    if (WingNameId != other.WingNameId) return false;
    if(!aAA_.Equals(other.aAA_)) return false;
    if (Int64Value != other.Int64Value) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (WingId != 0) hash ^= WingId.GetHashCode();
    if (Fighting != 0) hash ^= Fighting.GetHashCode();
    if (ImageName.Length != 0) hash ^= ImageName.GetHashCode();
    hash ^= itemInfo_.GetHashCode();
    hash ^= param_.GetHashCode();
    if (WingNameId != 0) hash ^= WingNameId.GetHashCode();
    hash ^= aAA_.GetHashCode();
    if (Int64Value != 0L) hash ^= Int64Value.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (WingId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(WingId);
    }
    if (Fighting != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Fighting);
    }
    if (ImageName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(ImageName);
    }
    itemInfo_.WriteTo(output, _repeated_itemInfo_codec);
    param_.WriteTo(output, _repeated_param_codec);
    if (WingNameId != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(WingNameId);
    }
    aAA_.WriteTo(output, _repeated_aAA_codec);
    if (Int64Value != 0L) {
      output.WriteRawTag(64);
      output.WriteInt64(Int64Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (WingId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(WingId);
    }
    if (Fighting != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Fighting);
    }
    if (ImageName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageName);
    }
    size += itemInfo_.CalculateSize(_repeated_itemInfo_codec);
    size += param_.CalculateSize(_repeated_param_codec);
    if (WingNameId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(WingNameId);
    }
    size += aAA_.CalculateSize(_repeated_aAA_codec);
    if (Int64Value != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Int64Value);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(WingUpLevel1Config other) {
    if (other == null) {
      return;
    }
    if (other.WingId != 0) {
      WingId = other.WingId;
    }
    if (other.Fighting != 0) {
      Fighting = other.Fighting;
    }
    if (other.ImageName.Length != 0) {
      ImageName = other.ImageName;
    }
    itemInfo_.Add(other.itemInfo_);
    param_.Add(other.param_);
    if (other.WingNameId != 0) {
      WingNameId = other.WingNameId;
    }
    aAA_.Add(other.aAA_);
    if (other.Int64Value != 0L) {
      Int64Value = other.Int64Value;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          WingId = input.ReadInt32();
          break;
        }
        case 16: {
          Fighting = input.ReadInt32();
          break;
        }
        case 26: {
          ImageName = input.ReadString();
          break;
        }
        case 34: {
          itemInfo_.AddEntriesFrom(input, _repeated_itemInfo_codec);
          break;
        }
        case 42:
        case 40: {
          param_.AddEntriesFrom(input, _repeated_param_codec);
          break;
        }
        case 48: {
          WingNameId = input.ReadInt32();
          break;
        }
        case 58: {
          aAA_.AddEntriesFrom(input, _repeated_aAA_codec);
          break;
        }
        case 64: {
          Int64Value = input.ReadInt64();
          break;
        }
      }
    }
  }

}

public sealed partial class WingUpLevel1ItemInfo : pb::IMessage<WingUpLevel1ItemInfo> {
  private static readonly pb::MessageParser<WingUpLevel1ItemInfo> _parser = new pb::MessageParser<WingUpLevel1ItemInfo>(() => new WingUpLevel1ItemInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<WingUpLevel1ItemInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WingUpLevel1ConfigReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WingUpLevel1ItemInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WingUpLevel1ItemInfo(WingUpLevel1ItemInfo other) : this() {
    itemId_ = other.itemId_;
    itemNum_ = other.itemNum_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WingUpLevel1ItemInfo Clone() {
    return new WingUpLevel1ItemInfo(this);
  }

  /// <summary>Field number for the "ItemId" field.</summary>
  public const int ItemIdFieldNumber = 1;
  private uint itemId_;
  /// <summary>
  ///ItemId===>初级经验丹id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint ItemId {
    get { return itemId_; }
    set {
      itemId_ = value;
    }
  }

  /// <summary>Field number for the "ItemNum" field.</summary>
  public const int ItemNumFieldNumber = 2;
  private uint itemNum_;
  /// <summary>
  ///ItemNum===>初级经验丹数量
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint ItemNum {
    get { return itemNum_; }
    set {
      itemNum_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as WingUpLevel1ItemInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(WingUpLevel1ItemInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ItemId != other.ItemId) return false;
    if (ItemNum != other.ItemNum) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ItemId != 0) hash ^= ItemId.GetHashCode();
    if (ItemNum != 0) hash ^= ItemNum.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ItemId != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(ItemId);
    }
    if (ItemNum != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(ItemNum);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ItemId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ItemId);
    }
    if (ItemNum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ItemNum);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(WingUpLevel1ItemInfo other) {
    if (other == null) {
      return;
    }
    if (other.ItemId != 0) {
      ItemId = other.ItemId;
    }
    if (other.ItemNum != 0) {
      ItemNum = other.ItemNum;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ItemId = input.ReadUInt32();
          break;
        }
        case 16: {
          ItemNum = input.ReadUInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class WingUpLevel1AAA : pb::IMessage<WingUpLevel1AAA> {
  private static readonly pb::MessageParser<WingUpLevel1AAA> _parser = new pb::MessageParser<WingUpLevel1AAA>(() => new WingUpLevel1AAA());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<WingUpLevel1AAA> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WingUpLevel1ConfigReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WingUpLevel1AAA() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WingUpLevel1AAA(WingUpLevel1AAA other) : this() {
    a1_ = other.a1_;
    uintA2_ = other.uintA2_;
    a3_ = other.a3_;
    repeatedA4_ = other.repeatedA4_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WingUpLevel1AAA Clone() {
    return new WingUpLevel1AAA(this);
  }

  /// <summary>Field number for the "A1" field.</summary>
  public const int A1FieldNumber = 1;
  private int a1_;
  /// <summary>
  ///A1===>A1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int A1 {
    get { return a1_; }
    set {
      a1_ = value;
    }
  }

  /// <summary>Field number for the "UintA2" field.</summary>
  public const int UintA2FieldNumber = 2;
  private uint uintA2_;
  /// <summary>
  ///UintA2===>UintA2
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint UintA2 {
    get { return uintA2_; }
    set {
      uintA2_ = value;
    }
  }

  /// <summary>Field number for the "A3" field.</summary>
  public const int A3FieldNumber = 3;
  private string a3_ = "";
  /// <summary>
  ///A3===>A3
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string A3 {
    get { return a3_; }
    set {
      a3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "RepeatedA4" field.</summary>
  public const int RepeatedA4FieldNumber = 4;
  private static readonly pb::FieldCodec<string> _repeated_repeatedA4_codec
      = pb::FieldCodec.ForString(34);
  private readonly pbc::RepeatedField<string> repeatedA4_ = new pbc::RepeatedField<string>();
  /// <summary>
  ///RepeatedA4===>RepeatedA4
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<string> RepeatedA4 {
    get { return repeatedA4_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as WingUpLevel1AAA);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(WingUpLevel1AAA other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (A1 != other.A1) return false;
    if (UintA2 != other.UintA2) return false;
    if (A3 != other.A3) return false;
    if(!repeatedA4_.Equals(other.repeatedA4_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (A1 != 0) hash ^= A1.GetHashCode();
    if (UintA2 != 0) hash ^= UintA2.GetHashCode();
    if (A3.Length != 0) hash ^= A3.GetHashCode();
    hash ^= repeatedA4_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (A1 != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(A1);
    }
    if (UintA2 != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(UintA2);
    }
    if (A3.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(A3);
    }
    repeatedA4_.WriteTo(output, _repeated_repeatedA4_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (A1 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(A1);
    }
    if (UintA2 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UintA2);
    }
    if (A3.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(A3);
    }
    size += repeatedA4_.CalculateSize(_repeated_repeatedA4_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(WingUpLevel1AAA other) {
    if (other == null) {
      return;
    }
    if (other.A1 != 0) {
      A1 = other.A1;
    }
    if (other.UintA2 != 0) {
      UintA2 = other.UintA2;
    }
    if (other.A3.Length != 0) {
      A3 = other.A3;
    }
    repeatedA4_.Add(other.repeatedA4_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          A1 = input.ReadInt32();
          break;
        }
        case 16: {
          UintA2 = input.ReadUInt32();
          break;
        }
        case 26: {
          A3 = input.ReadString();
          break;
        }
        case 34: {
          repeatedA4_.AddEntriesFrom(input, _repeated_repeatedA4_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
